kind: Deployment
apiVersion: apps/v1
metadata:
  name: mq-producer
  namespace: mq-demo
  labels:
    app: mq-producer
    app.kubernetes.io/component: mq-producer
    app.kubernetes.io/instance: mq-producer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: mq-producer
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: mq-producer
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: mq-producer
          image: 'image-registry.openshift-image-registry.svc:5000/mq-demo/mq-producer@sha256:b500c592f3ab398d09310a777b6aae6c20026fd717620ab9e9d35d9c5726bfdc'
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          env:
            - name: JAVA_APP_JAR
              value: producer-1.0-SNAPSHOT-jar-with-dependencies.jar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
