kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: mq-demo
  labels:
    app: mq-consumer
    app.kubernetes.io/component: mq-consumer
    app.kubernetes.io/instance: mq-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: mq-consumer
  template:
    metadata:
      creationTimestamp: null
      labels:
        deployment: mq-consumer
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
    spec:
      containers:
        - name: mq-consumer
          image: ' '
          ports:
            - containerPort: 8080
              protocol: TCP
            - containerPort: 8443
              protocol: TCP
            - containerPort: 8778
              protocol: TCP
          env:
            - name: JAVA_APP_JAR
              value: consumer-1.0-SNAPSHOT-jar-with-dependencies.jar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
