kind: Service
apiVersion: v1
metadata:
  name: mq-producer
  namespace: mq-demo
  labels:
    app: mq-producer
    app.kubernetes.io/component: mq-producer
    app.kubernetes.io/instance: mq-producer
  annotations:
    openshift.io/generated-by: OpenShiftNewApp
spec:
  clusterIP: 172.30.90.27
  ipFamilies:
    - IPv4
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: 8443-tcp
      protocol: TCP
      port: 8443
      targetPort: 8443
    - name: 8778-tcp
      protocol: TCP
      port: 8778
      targetPort: 8778
  internalTrafficPolicy: Cluster
  clusterIPs:
    - 172.30.90.27
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    deployment: mq-producer
